apiVersion: v2
name: comfyui
description: A Helm chart for deploying ComfyUI — a powerful and modular stable diffusion GUI — on Kubernetes with GPU support.
type: application
version: 0.6.1
appVersion: "cu130-megapak-pt211"
home: https://github.com/Comfy-Org/ComfyUI
sources:
  - https://github.com/mmmateusz/comfyui-helm-chart
keywords:
  - comfyui
  - stable-diffusion
  - ai
  - machine-learning
  - gpu
  - image-generation
maintainers:
  - name: mmateusz
    email: mateusz@sowa-it.com
icon: https://raw.githubusercontent.com/mmmateusz/comfyui-helm-chart/main/assets/comfy_ui.png
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/changes: |
    - Added simple connection test
